import io
import os
from typing import Dict, Any
from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, HRFlowable


class ReportService:
    """
    Generates downloadable PDF assessment reports formatted with clean healthcare styling,
    structured metric summaries, and required medical safety disclaimers.
    """
    def generate_pdf_report(self, assessment_data: Dict[str, Any]) -> io.BytesIO:
        buffer = io.BytesIO()
        doc = SimpleDocTemplate(
            buffer,
            pagesize=letter,
            rightMargin=36,
            leftMargin=36,
            topMargin=36,
            bottomMargin=36
        )

        styles = getSampleStyleSheet()
        
        # Custom Typography Styles
        title_style = ParagraphStyle(
            "ReportTitle",
            parent=styles["Heading1"],
            fontSize=22,
            leading=26,
            textColor=colors.HexColor("#0F172A"),
            fontName="Helvetica-Bold",
            spaceAfter=4
        )
        subtitle_style = ParagraphStyle(
            "ReportSubtitle",
            parent=styles["Normal"],
            fontSize=11,
            leading=14,
            textColor=colors.HexColor("#64748B"),
            spaceAfter=14
        )
        section_heading = ParagraphStyle(
            "SectionHeading",
            parent=styles["Heading2"],
            fontSize=13,
            leading=16,
            textColor=colors.HexColor("#1E293B"),
            fontName="Helvetica-Bold",
            spaceBefore=12,
            spaceAfter=6
        )
        body_style = ParagraphStyle(
            "ReportBody",
            parent=styles["Normal"],
            fontSize=9,
            leading=12,
            textColor=colors.HexColor("#334155")
        )
        disclaimer_style = ParagraphStyle(
            "DisclaimerStyle",
            parent=styles["Normal"],
            fontSize=8,
            leading=11,
            textColor=colors.HexColor("#991B1B"),
            fontName="Helvetica-Oblique"
        )

        story = []

        # 1. Header Banner
        story.append(Paragraph("HEARTGUARD AI", title_style))
        story.append(Paragraph("AI-Powered Heart Disease Risk Assessment & Lifestyle Intelligence Report", subtitle_style))
        story.append(HRFlowable(width="100%", thickness=1.5, color=colors.HexColor("#E2E8F0"), spaceAfter=10))

        # 2. Disclaimer Alert Box
        disclaimer_text = (
            "<b>IMPORTANT EDUCATIONAL NOTICE:</b> This report is generated by algorithmic machine learning "
            "models (DNN, MLP, TabNet) strictly for educational exploration. It is <b>NOT</b> a clinical medical "
            "diagnosis or physician confirmation. Consult a licensed medical professional for personal cardiovascular care."
        )
        disclaimer_table = Table(
            [[Paragraph(disclaimer_text, disclaimer_style)]],
            colWidths=[540]
        )
        disclaimer_table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#FEF2F2")),
            ("BOX", (0, 0), (-1, -1), 1, colors.HexColor("#FECACA")),
            ("TOPPADDING", (0, 0), (-1, -1), 8),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
            ("LEFTPADDING", (0, 0), (-1, -1), 10),
            ("RIGHTPADDING", (0, 0), (-1, -1), 10),
        ]))
        story.append(disclaimer_table)
        story.append(Spacer(1, 12))

        # 3. Assessment Metadata & Patient Profile
        hd = assessment_data.get("health_data", {})
        created_at = assessment_data.get("created_at", "N/A")[:19].replace("T", " ")
        doc_id = assessment_data.get("id", "N/A")[:8]

        profile_data = [
            [
                Paragraph(f"<b>Assessment ID:</b> {doc_id}", body_style),
                Paragraph(f"<b>Date:</b> {created_at} UTC", body_style),
                Paragraph(f"<b>Patient:</b> {assessment_data.get('patient_name', 'Anonymous')}", body_style)
            ],
            [
                Paragraph(f"<b>Age:</b> {hd.get('age', 'N/A')} yrs", body_style),
                Paragraph(f"<b>Sex:</b> {'Male' if hd.get('sex') == 1 else 'Female'}", body_style),
                Paragraph(f"<b>Resting BP:</b> {hd.get('trestbps', 'N/A')} mmHg", body_style)
            ],
            [
                Paragraph(f"<b>Cholesterol:</b> {hd.get('chol', 'N/A')} mg/dL", body_style),
                Paragraph(f"<b>Max HR:</b> {hd.get('thalach', 'N/A')} bpm", body_style),
                Paragraph(f"<b>ST Depression:</b> {hd.get('oldpeak', 'N/A')} mm", body_style)
            ]
        ]
        meta_table = Table(profile_data, colWidths=[180, 180, 180])
        meta_table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#F8FAFC")),
            ("BOX", (0, 0), (-1, -1), 1, colors.HexColor("#E2E8F0")),
            ("INNERGRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#E2E8F0")),
            ("TOPPADDING", (0, 0), (-1, -1), 5),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
        ]))
        story.append(meta_table)
        story.append(Spacer(1, 10))

        # 4. Estimated Risk & Multi-Model Breakdown
        story.append(Paragraph("1. Estimated Risk & Multi-Model Analysis", section_heading))
        
        risk_pct = assessment_data.get("risk_percentage", 0.0)
        risk_cat = assessment_data.get("risk_category", "N/A")
        dnn_p = round(float(assessment_data.get("dnn_probability", 0.0)) * 100, 1)
        mlp_p = round(float(assessment_data.get("mlp_probability", 0.0)) * 100, 1)
        tabnet_p = round(float(assessment_data.get("tabnet_probability", 0.0)) * 100, 1)

        model_data = [
            [
                Paragraph("<b>Ensemble Risk</b>", body_style),
                Paragraph("<b>Deep Neural Net (DNN)</b>", body_style),
                Paragraph("<b>Multi-Layer Perceptron (MLP)</b>", body_style),
                Paragraph("<b>TabNet Classifier</b>", body_style)
            ],
            [
                Paragraph(f"<b><font size=12 color='#E11D48'>{risk_pct}%</font></b><br/>{risk_cat}", body_style),
                Paragraph(f"<b>{dnn_p}%</b><br/>4 Dense Layers", body_style),
                Paragraph(f"<b>{mlp_p}%</b><br/>2-Layer Baseline", body_style),
                Paragraph(f"<b>{tabnet_p}%</b><br/>Attentive Steps", body_style)
            ]
        ]
        model_table = Table(model_data, colWidths=[135, 135, 135, 135])
        model_table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#FFFFFF")),
            ("BOX", (0, 0), (-1, -1), 1, colors.HexColor("#CBD5E1")),
            ("INNERGRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#E2E8F0")),
            ("TOPPADDING", (0, 0), (-1, -1), 6),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
        ]))
        story.append(model_table)
        story.append(Spacer(1, 10))

        # 5. Top Influencing Factors (Explainable AI)
        story.append(Paragraph("2. Primary Risk Drivers & Protective Biomarkers (XAI)", section_heading))
        factors = assessment_data.get("top_factors", [])[:5]
        factor_rows = [
            [Paragraph("<b>Biomarker</b>", body_style), Paragraph("<b>Measured Value</b>", body_style), Paragraph("<b>Impact Direction</b>", body_style), Paragraph("<b>Clinical Rationale</b>", body_style)]
        ]
        for f in factors:
            dir_text = "<font color='#DC2626'><b>Elevates Risk</b></font>" if f.get("direction") == "elevates_risk" else "<font color='#059669'><b>Protective</b></font>"
            factor_rows.append([
                Paragraph(f.get("feature_name", ""), body_style),
                Paragraph(str(f.get("display_value", "")), body_style),
                Paragraph(dir_text, body_style),
                Paragraph(f.get("clinical_insight", ""), body_style)
            ])

        factor_table = Table(factor_rows, colWidths=[110, 85, 95, 250])
        factor_table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#F1F5F9")),
            ("BOX", (0, 0), (-1, -1), 1, colors.HexColor("#CBD5E1")),
            ("INNERGRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#E2E8F0")),
            ("TOPPADDING", (0, 0), (-1, -1), 4),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
        ]))
        story.append(factor_table)
        story.append(Spacer(1, 10))

        # 6. Actionable Lifestyle Recommendations
        story.append(Paragraph("3. General Lifestyle Guidance Pillars", section_heading))
        recs = assessment_data.get("recommendations", [])[:4]
        rec_rows = []
        for r in recs:
            pts = "<br/>• ".join(r.get("actionable_points", [])[:2])
            rec_rows.append([
                Paragraph(f"<b>{r.get('category', '')}: {r.get('title', '')}</b><br/>• {pts}", body_style)
            ])
        rec_table = Table(rec_rows, colWidths=[540])
        rec_table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#F8FAFC")),
            ("BOX", (0, 0), (-1, -1), 1, colors.HexColor("#E2E8F0")),
            ("INNERGRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#E2E8F0")),
            ("TOPPADDING", (0, 0), (-1, -1), 5),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
        ]))
        story.append(rec_table)
        story.append(Spacer(1, 12))

        # 7. Physician Discussion Topics
        physician_guide = (
            "<b>Topics to Discuss With Your Doctor:</b><br/>"
            "1. Discuss your current blood pressure trend and whether home log records are advised.<br/>"
            "2. Review your latest lipid panel (LDL, HDL, Triglycerides, ApoB) for atherosclerosis risk.<br/>"
            "3. Inquire whether an in-office 12-lead ECG, stress echocardiogram, or coronary calcium scoring is suitable."
        )
        story.append(Paragraph(physician_guide, body_style))

        # Build document
        doc.build(story)
        buffer.seek(0)
        return buffer


report_service = ReportService()
